import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {initAuth,createAccount} from './auth.mjs';
test('approval, sessions, CSRF, privacy and server ownership enforcement',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'univfolio-auth-')),port=30000+Math.floor(Math.random()*10000),origin=`http://127.0.0.1:${port}`;
 const db=new DatabaseSync(join(dir,'db.sqlite'));initAuth(db);
 const password='Long-test-password-123';
 await createAccount(db,{email:'admin@test.com',password,realName:'운영자',studentId:'admin',department:'운영'},true);
 const child=spawn(process.execPath,['server/index.mjs'],{env:{...process.env,DB_PATH:join(dir,'db.sqlite'),API_PORT:String(port),COOKIE_SECURE:'true',PUBLIC_ORIGIN:origin},stdio:'pipe'});
 const request=async(path,payload,session,headers={})=>{const r=await fetch(`${origin}/api/${path}`,{method:payload?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{}),...headers},...(payload?{body:JSON.stringify(payload)}:{})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')};};
 const login=async email=>{const r=await request('auth/login',{email,password});assert.equal(r.status,200);assert.match(r.cookie,/HttpOnly/);assert.match(r.cookie,/SameSite=Lax/);assert.match(r.cookie,/Secure/);return {cookie:r.cookie.split(';')[0],csrf:r.data.csrf,id:r.data.user.id};};
 try{
  for(let i=0;i<100;i++){try{if((await fetch(`${origin}/api/health`)).ok)break;}catch{}await new Promise(r=>setTimeout(r,50));}
  assert.equal((await request('state',undefined,null,{'X-Demo-User':'admin'})).status,401);
  assert.equal((await request('action',{action:'delete',id:'x'})).status,401);
  const admin=await login('admin@test.com');
  const input={email:'student@test.com',password,realName:'학생',studentId:'2026001',department:'영상',role:'admin',status:'재학생',isVerified:true};
  assert.equal((await request('auth/signup',input)).status,200);
  assert.equal((await request('auth/signup',input)).status,409);
  assert.equal((await request('auth/login',{email:input.email,password})).status,403);
  assert.equal((await request('auth/login',{email:input.email,password:'wrong'})).status,401);
  const users=(await request('admin/users',undefined,admin)).data.users;
  const student=users.find(u=>u.email===input.email);assert.equal(student.role,'member');assert.equal(student.profile.isVerified,false);assert.equal(student.password,undefined);
  assert.equal((await request('admin/review',{id:student.id,status:'approved'},admin,{'X-CSRF-Token':'wrong'})).status,403);
  assert.equal((await request('admin/review',{id:student.id,status:'approved'},admin,{Origin:'https://evil.example'})).status,403);
  assert.equal((await request('admin/review',{id:student.id,status:'approved'},admin)).status,200);
  const member=await login(input.email);
  assert.equal((await request('admin/users',undefined,member)).status,403);
  assert.equal((await request('admin/review',{id:student.id,status:'approved'},member)).status,403);
  const initial=(await request('state',undefined,admin)).data;
  const project={...initial.projects[0],id:'private-test',isPublished:false,revision:undefined};
  assert.equal((await request('action',{action:'save',kind:'projects',item:project},member)).status,200);
  let own=(await request('state',undefined,member)).data.projects.find(p=>p.id===project.id);
  assert.equal(own.author.id,member.id);assert.equal(own.author.isVerified,false);
  const otherInput={...input,email:'other@test.com',studentId:'2026002'};
  await request('auth/signup',otherInput);const otherId=db.prepare('SELECT id FROM accounts WHERE email=?').get(otherInput.email).id;
  await request('admin/review',{id:otherId,status:'approved'},admin);const other=await login(otherInput.email);
  assert.equal((await request('state',undefined,other)).data.projects.some(p=>p.id===project.id),false);
  for(const action of ['delete','publish','like','view','comment']) assert.equal((await request('action',{action,id:project.id,content:'spoof'},other)).status,403);
  assert.equal((await request('action',{action:'save',kind:'projects',item:own},other)).status,403);
  assert.equal((await request('action',{action:'save',kind:'profiles',item:own.author},other)).status,403);
  assert.equal((await request('action',{action:'import',projects:[]},member)).status,403);
  const spoof={...own.author,isVerified:true,studentId:'fake',realName:'fake',bio:'Updated'};
  await request('action',{action:'save',kind:'profiles',item:spoof},member);
  const me=(await request('auth/me',undefined,member)).data.user;assert.equal(me.realName,'학생');assert.equal(me.isVerified,false);assert.equal(me.bio,'Updated');
  await request('action',{action:'publish',id:project.id},member);
  const publicProject=(await request('state',undefined,other)).data.projects.find(p=>p.id===project.id);assert.equal(publicProject.author.studentId,'');assert.equal(publicProject.author.links.email,'');
  await request('action',{action:'comment',id:project.id,content:'Hi',author:own.author},other);
  assert.equal((await request('state',undefined,member)).data.projects.find(p=>p.id===project.id).comments[0].author.id,other.id);
  await request('admin/review',{id:student.id,status:'suspended',reason:'test'},admin);
  assert.equal((await request('state',undefined,member)).status,401);
  assert.equal((await request('auth/login',{email:input.email,password})).status,403);
  assert.equal(db.prepare('SELECT count(*) n FROM auth_audit WHERE target=?').get(student.id).n,2);
  assert.notEqual(db.prepare('SELECT password FROM accounts WHERE id=?').get(student.id).password,password);
  await request('auth/logout',{},other);assert.equal((await request('state',undefined,other)).status,401);
  const third={...input,email:'rejected@test.com'};await request('auth/signup',third);const rejected=db.prepare('SELECT id FROM accounts WHERE email=?').get(third.email).id;await request('admin/review',{id:rejected,status:'rejected'},admin);assert.equal((await request('auth/login',{email:third.email,password})).status,403);
 } finally {const done=once(child,'exit');child.kill();await done;db.close();rmSync(dir,{recursive:true,force:true});}
});
